services:
  njpc:
    build:
      context: .
      dockerfile: Dockerfile
    image: njpc:local
    container_name: njpc
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - NODE_ENV=production
      # Example overrides as supported by Config.getEnvVariables()
      # - POOL_WEB_SERVERS_HTTP_PORT=4200
    ports:
      - "4200:4200"   # HTTP
      - "4201:4201"   # HTTPS (if enabled)

    #volumes:
    #  - ./data:/app/data
    #  - ./backups:/app/backups
    #  - ./logs:/app/logs

    # Map RS-485 USB adapter if present, adjust device path
    # devices:
    #   - /dev/ttyACM0:/dev/ttyUSB0